### ISSUE TITLE
Claims Retrieval Issue in SqlIdentityHubStore Due to Missing payloadFormat

### ISSUE THREAD

**Issue by konrad1adamczyk** [eclipse-edc/IdentityHub#107]
# Bug Report

## Describe the Bug
payloadFormat is not being added in the SqlIdentityHubStore and therefore the claims cannot be retrieved in the other functions.

### Expected Behavior
When the sql store of identity hub is being used, the claims should be retrieved.

### Observed Behavior
When the sql store of identity hub is being used, the claims cannot be retrieved.

## Detailed Description
The issue with the current implementation of the SqlIdentityHubStore is that the payloadFormat is not being added, resulting in the inability to retrieve claims in other functions.
To resolve this issue, the payloadFormat needs to be included in the code of the SqlIdentityHubStore. One possible implementation for this is to add the line of code from: Possible Implementation
It is important to thoroughly test this solution to ensure that it resolves the problem and does not introduce any unforeseen issues.
Please note that this detailed description provides an overview of the issue and suggests a potential solution. Further investigation and analysis may be required to fully address the problem.

## Possible Implementation
.payloadFormat(resultSet.getString(statements.getPayloadFormatColumn()))

**Comment by bscholtes1A** [comment]
Fixed by https://github.com/eclipse-edc/IdentityHub/pull/112

**Comment by bscholtes1A** [comment]
Fixed by https://github.com/eclipse-edc/IdentityHub/pull/112
