### ISSUE TITLE
Lacking E2E tests

### ISSUE THREAD

**Issue by Yalz** [eclipse-edc/IdentityHub#210]
# Feature Request

## Which Areas Would Be Affected?
E2E Tests

## Why Is the Feature Desired?
As a party interested in using the IdentityHub, I want to work with practical examples.
However, the current tests in the e2e module are practically Unit tests where you verify the API endpoints of the Presentation Controller.

## Solution Proposal
Based on the graphs provided in the [docs](https://github.com/eclipse-edc/IdentityHub/tree/main/docs/developer/decision-records/2022-06-08-identity-hub), a fully explained step by step e2e would be helpful to understand the Identity Hub without having to dive into the code.

**Comment by paullatzelsperger** [comment]
There is quite a substantial refactoring ongoing in the upstream project (https://github.com/eclipse-edc/Connector/issues/3743), which will most likely have an impact here too. That is why we still have mocks as opposed to: the real thing in the test you mentioned.

That being said: the test is **not** a unit test as it actually spins up the entire IdentityHub in-process. That is why it is annotated with `@ComponentTest`. 

## Most importantly though:

The decision-record you mentioned is **outdated** and was superseded by [this decision-record](https://github.com/eclipse-edc/IdentityHub/tree/main/docs/developer/decision-records/2023-09-27-adoption_of_the_identity_and_trust_protocol). If you want get familiar with the IATP specs that supersede the DWN implementation, I recommend taking a look at their [current (temporary) home](https://github.com/eclipse-tractusx/identity-trust/tree/main/specifications/M1).

I'll leave this issue open for now, but we may need to update the description to fit the current situation

**Comment by Yalz** [comment]
Hi Paul, 

I understand the refactoring going around. However what I'm lacking is something similar to your work in the [Federated Catalog E2E Test](https://github.com/eclipse-edc/FederatedCatalog/tree/main/system-tests/end2end-test).

Since this would make the adoption of the IdentityHub a tremendous lot easier

**Comment by xdxxxdx** [comment]
Hello @paullatzelsperger ,
Thanks for the reply.
I would like to understand if this IATP spec going to implement: https://openid.net/sg/openid4vc/ flow.
If there is an edc project implement the https://openid.net/sg/openid4vc/ flow?
Thanks

**Comment by paullatzelsperger** [comment]
> Hi Paul,
> 
> I understand the refactoring going around. However what I'm lacking is something similar to your work in the [Federated Catalog E2E Test](https://github.com/eclipse-edc/FederatedCatalog/tree/main/system-tests/end2end-test).
> 
> Since this would make the adoption of the IdentityHub a tremendous lot easier

Proper E2E Tests are on our plan, although for the time being, they are not the top priority. I would recommend periodically checking back, as IdentityHub receives a lot of updates these days.

**Comment by paullatzelsperger** [comment]
> Hello @paullatzelsperger , Thanks for the reply. I would like to understand if this IATP spec going to implement: https://openid.net/sg/openid4vc/ flow. If there is an edc project implement the https://openid.net/sg/openid4vc/ flow? Thanks

No, neither IdentityHub nor any other EDC component will implement OIDC4VC or any related specs, as they are really geared toward a physical user and most likely a mobile device, whereas IATP is geared towards an organizational entity and machine-to-machine communication.

**Comment by xdxxxdx** [comment]
> > Hello @paullatzelsperger , Thanks for the reply. I would like to understand if this IATP spec going to implement: https://openid.net/sg/openid4vc/ flow. If there is an edc project implement the https://openid.net/sg/openid4vc/ flow? Thanks
> 
> No, neither IdentityHub nor any other EDC component will implement OIDC4VC or any related specs, as they are really geared toward a physical user and most likely a mobile device, whereas IATP is geared towards an organizational entity and machine-to-machine communication.
> 
> @xdxxxdx In the future, please open a Discussion instead of asking random questions on unrelated issues.

Thanks for the reply.
