### ISSUE TITLE
ParticipantContextServiceImpl createParticipantContext does not configure did

### ISSUE THREAD

**Issue by ThomasRutger** [eclipse-edc/IdentityHub#347]
# Bug Report

## Describe the Bug
When a new participant is created using ParticipantContextServiceImpl.createParticipantContext, did is not configured.

### Expected Behavior
Did to be set according to the ParticipantManifest.

### Observed Behavior
Did is set to null.

## Steps to Reproduce
Create a ParticipantManifest (with did) and create a ParticipantContext using ParticipantContextServiceImpl.createParticipantContext. When retrieving the newly created ParticipantContext object, did will be null.

## Possible Implementation
Call the did builder method in convert, using the did as defined in the manifest

**Comment by paullatzelsperger** [comment]
This is not a bug. Please take a look at the `ParticipantContextEventCoordinator`, which will receive the `ParticipantContextCreatedEvent` and then call the `DidDocumentService`.

**Comment by ThomasRutger** [comment]
> Not sure this is a bug. Please take a look at the `ParticipantContextEventCoordinator`, which will receive the `ParticipantContextCreatedEvent` and then call the `DidDocumentService`. When resolving DID documents for a participant, we always go through the ParticipantContext database entry.

Not sure I fully understand. I did check out  `ParticipantContextEventCoordinator` and noticed a DID document is created there based on the manifest.

Basically I have a participantId and I want to get the associated did for that Participant. I am unable to use ParticipantContextService to get the did as it never seems to be set and so it returns null.

**Comment by paullatzelsperger** [comment]
> Basically I create a participant during startup, call participantContextService.createParticipantContext etc., then later I have a participantId and I want to get the associated did for that Participant. I am unable to use ParticipantContextService to get the did as it never seems to be set and so it returns null.


The `ParticipantContextService` is not intended to do that, if you want to get a DID Document for a participant, you'll need to use the `DidDocumentService#queryDocuments` method supplying a QuerySpec like:
```java
QuerySpec.Builder.newInstance()
                .filter(new Criterion("participantId", "=", participantId))
                .build()
```

I did notice however, that the `ParticipantContext#did` property is not set correctly (which I think is what you meant). 
Once that is fixed, you can use `participantContext.getDid()` and then `DidDocumentService#findbyId()`
