### ISSUE TITLE
JwtPresentationGenerator.generatePresentation adds incorrect public key id to VP

### ISSUE THREAD

**Issue by thomasrutger** [eclipse-edc/IdentityHub#407]
# Bug Report

## Describe the Bug

It seems that in `JwtPresentationGenerator.generatePresentation`. The public key id is incorrectly set. This is because the `additionalData[CONTROLLER_ADDITIONAL_DATA]` that is set in `VerifiablePresentationServiceImpl.createPresentation` is set to the `participantContextId`, instead of the participants' DID.  `JwtPresentationGenerator.generatePresentation` uses the controllerId to check if the publicKey id is correctly formatted,but since this is not the DID it will not yield the desired result.

This for me is resulting in incorrectly formatted public key ids. eg when my public key id is `did:web:example#example-key` it gets formatted as example#did:web:example#example-key`.

in the `JwtPresentationGeneratorTest` the controller is correctly set to a did and not a participantContextId.

I haven't tested, but `LdpPresentationGenerator` might have the same problem.

### Expected Behavior
I expect the keyId to be correctly formatted.

### Observed Behavior

Incorrectly formatted public keyId, verifier cannot verify the VP.

## Context Information

_Add any other context about the problem here._

version: 0.8.1-SNAPSHOT

## Possible Implementation

Possible solutions:
- Use the `publicKeyId` as is and assume it is already encoded as the DID fragment.
- Add the controller DID to additional data map only in `PresentationCreatorRegistryImpl.createPresentation`, after the DID has been resolved.
- Add the DID as `CONTROLLER_ADDITIONAL_DATA` instead of the participantContextId. Then pass both the DID and participantContextId to `PresentationCreatorRegistryImpl.createPresentation`, so it does not have the be resololved twice.
- Use a PresentationParameters class of sorts with a Builder (possibly use decorators (like TokenParameters)).

**Comment by thomasrutger** [comment]
Yes, but `additionalData[CONTROLLER_ADDITIONAL_DATA]` contains the participantContextId and not the DID, which I think it should be? See:

https://github.com/eclipse-edc/IdentityHub/blob/c444f67f0f6e3bae58f29c805376ee8da0f4061c/core/lib/verifiable-presentation-lib/src/main/java/org/eclipse/edc/identithub/verifiablepresentation/VerifiablePresentationServiceImpl.java#L82-L84

**Comment by paullatzelsperger** [comment]
ah I see, yes, that seems incorrect. I guess a good way to solve this, would be to add the `"controller"` entry in the `PresentationCreatorRegistryImpl#createPresentation` method, since we already resolve the `did` there anyway

**Comment by thomasrutger** [comment]
That is pretty much exactly my local workaround indeed, seems like the best way to fix it. Would it be alright if I submit a pull request with the changes?

**Comment by paullatzelsperger** [comment]
> That is pretty much exactly my local workaround indeed, seems like the best way to fix it. Would it be alright if I submit a pull request with the changes?

sure go ahead :)
