### ISSUE TITLE
Typo in Log Message: 'SecureTokenService (STS)' should be 'AccountService'

### ISSUE THREAD

**Issue by thomasrutger** [eclipse-edc/IdentityHub#479]
# Bug Report

## Describe the Bug

In StsAccountProvisionerExtension.accountManager, if no injected StsAccountService is found it logs a warning:

```
"This IdentityHub runtime does NOT contain an embedded SecureTokenService (STS) instance and no remote STS was configured. " +
                    "Synchronizing ParticipantContexts and STS Accounts must be handled out-of-band."
```

### Expected Behavior

I think SecureTokenService is a typo and should be StsAccountService, or something similar like "account service".

**Comment by paullatzelsperger** [comment]
actually, I think the log-line is correct, because the actual situation is that the STS is not embedded, nor was a remote STS configured. This may very well be expected, e.g. when using a custom STS implementation, that does not allow account synchronization.

The fact that the `StsAccountService` is not present is just a consequence and is an implementation detail.

**Comment by thomasrutger** [comment]
> actually, I think the log-line is correct, because what's relevant for the user is that the STS is not embedded, nor was a remote STS configured. As a consequence, account sync won't work. That said, this situation may very well be expected, e.g. when using a custom STS implementation, that does not allow account synchronization.
> 
> The fact that the `StsAccountService` is not present is just an implementation detail and users may not care about it.

I was having trouble understanding what was being implied. I forgot to include the Account Service as a dependency during my upgrade, but the message seemed to imply it was about not having  a SecureTokenService available, which seemed odd to me. I realize now that I misinterpreted the log message. Thanks for clarifying this.
