### ISSUE TITLE
java.lang.ClassNotFoundException: org.eclipse.edc.boot.system.runtime.BaseRuntime

### ISSUE THREAD

**Issue by dotChris90** [eclipse-edc/IdentityHub#89]
# Bug Report

## Describe the Bug
I cannot run IdentityHub because missing Baseruntime

### Expected Behavior

- ./gradlew :launer:build #to build the Hub
- java -jar identity-hub.jar # to run the Hub

### Observed Behavior
I get an error org.eclipse.edc.boot.system.runtime.Baseruntime missing

## Steps to Reproduce
- see expected behavior

## Context Information

- Used version [e.g. IdentityHub v1.0.0]
- OS: Linux Ubuntu 22.04 
- using branch releases and main - both fail

## Possible Implementation
- maybe missing the baseruntime? or did i miss sth?

**Comment by dotChris90** [comment]
HINT : I followed the instructions
cd <DataSpaceConnector-root-folder>
# Use the same commit as CD pipeline to make sure it is compatible with the EDC version. See ref field on [action.yml](.github/actions/gradle-setup/action.yml)
git checkout 5191d3e6dd9ac5d78264d05ae69edb4d297b606a
./gradlew publishToMavenLocal -Pskip.signing

but still no success.

**Comment by bscholtes1A** [comment]
Hello @dotChris90 
Should be fixed with this PR https://github.com/eclipse-edc/IdentityHub/pull/91 which improves the documentation so that you can deploy your Identity Hub instance.

**Comment by dotChris90** [comment]
thank you! :D
