### ISSUE TITLE
Error while adding the Verifiable credential to the Identity Hub

### ISSUE THREAD

**Issue by dotChris90** [eclipse-edc/IdentityHub#92]
# Bug Report

## Describe the Bug
I was looking in the system-test folder and was debugging the integration test so that i can use it by myself without debugging the system integration test.  

### Expected Behavior
VC would be added to hub just like in integration test 

### Observed Behavior
i got error "Error while adding the Verifiable credential to the Identity Hub"

## Steps to Reproduce

1st starting the identity hub by "java -jar launcher/build/libs/identity-hub.jar"
2nd starting the did servers with docker-compose (or python -m http.server 8080) by "docker-compose -f system-tests/docker-compose.yml up --build"
3rd using the command line to add VC by "java -jar ../identity-hub-cli/build/libs/identity-hub-cli.jar -s ..." (for detailed arguments see picture attached )

## Detailed Description
I was starting the hub without dockerfile, i was starting the did server in container environment but checked via curl and firefox that localhost:8080 was reachable, at end got adding VC error. 

My question would be simple : did i sth wrong or i miss sth? 

Arguments are just like in system-test :

![2023-03-13_09h05_28](https://user-images.githubusercontent.com/33638852/224657079-0272d186-aeb8-4c68-b14f-4a880329abf5.png)
![2023-03-13_10h59_43](https://user-images.githubusercontent.com/33638852/224668865-07b5a40b-7d1b-4dc3-8266-6ba8cddfd050.png)

ERROR : 
on hub side:
![2023-03-13_10h53_36](https://user-images.githubusercontent.com/33638852/224668351-b514e836-562e-46b4-9408-c09dac65fd9a.png)

on cli side:
![2023-03-13_10h53_20](https://user-images.githubusercontent.com/33638852/224668396-28c41630-5f39-478d-8b16-e779aaa9a339.png)

- Used version [e.g. master branch]
- OS:  Ubuntu 2022-04 - in Virtualbox

**Comment by alperbasak** [comment]
It might be obsolete at this point but  if you still are looking for the resolution, include `project(":extensions:credentials:identity-hub-credentials-jwt")` as a dependency to your launcher. That extension adds the support for `application/vc+jwt` (which the `cli` makes use of)

**Comment by bscholtes1A** [comment]
Closing this issue as it's stale for more than 1 month now.
